name: Zip EPUBs
on: push
jobs:
  epub-zip:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout main
        uses: actions/checkout@v2
        with:
          path: main

      - name: zip
        run: |
          cd main
          chmod +x .github/workflows/deterministic-zip
          sudo mv .github/workflows/deterministic-zip /usr/local/bin/deterministic-zip
          find . -maxdepth 2 -mindepth 2 -not -path '*/.*' -type d -exec bash -c "cd \"{}\" && cd foreign && deterministic-zip -r ../foreign.zip * && cd .. && mv foreign.zip foreign.epub && rm -rf foreign && cd english && deterministic-zip -r ../english.zip * && cd .. && mv english.zip english.epub && rm -rf english" \;
          rm -rf .github book_information.json LICENSE README.md .git
          
      - name: checkout zip
        uses: actions/checkout@v2
        with:
          ref: zip
          path: zip
          
      - name: commit zip
        run: |
          cp -r zip/.git main/.git
          cd main
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add --all
          { git diff --name-only ; git diff --name-only --staged ; } | sort | uniq > ../changes
          git commit -m "automated: zipping into .epub"
          git push --force --set-upstream origin zip
          echo "LAST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "COMMIT_TIME=$(git show -s --format=%ct $LAST_COMMIT)" >> $GITHUB_ENV
          
      - name: checkout main again
        uses: actions/checkout@v2
        with:
          path: main_again
          
      - name: update book
        run: |
          cd main_again
          python .github/workflows/update_json.py ../changes $LAST_COMMIT $COMMIT_TIME book_information.json
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add book_information.json
          git commit -m "automated: updating book_information.json for commit $LAST_COMMIT"
          git push
          
