name: Zip EPUBs
on: push
jobs:
  epub-zip:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: zip
        run: |
          pwd
          ls -la
          chmod +x .github/workflows/deterministic-zip
          sudo mv .github/workflows/deterministic-zip /usr/local/bin/deterministic-zip
          find . -maxdepth 2 -mindepth 2 -not -path '*/.*' -type d -exec bash -c "cd \"{}\" && cd foreign && deterministic-zip -r ../foreign.epub * && cd .. && rm -rf foreign && cd english && deterministic-zip -r ../english.epub * && cd .. && rm -rf english" \;
          rm -rf .github book_information.json LICENSE README.md
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git checkout --detach
          git reset --soft refs/remotes/zip
          git checkout refs/remotes/zip
          git add --all
          git commit -m "automated: zipping into .epub"
          git push --force --set-upstream origin zip
